return {}

-- vim.api.nvim_set_keymap('n', 'W', '<Plug>CamelCaseMotion_w', {noremap = false, silent = true})
-- vim.api.nvim_set_keymap('n', 'B', '<Plug>CamelCaseMotion_b', {noremap = false, silent = true})
-- vim.api.nvim_set_keymap('n', 'E', '<Plug>CamelCaseMotion_e', {noremap = false, silent = true})
-- -- vim.api.nvim_set_keymap('n', 'ge', '<Plug>CamelCaseMotion_ge', {noremap = false, silent = true})
-- -- vim.cmd([[sunmap W]])
-- -- vim.cmd([[sunmap B]])
-- -- vim.cmd([[sunmap E]])
-- -- vim.cmd([[sunmap ge]])
-- vim.api.nvim_set_keymap('o', 'iW', '<Plug>CamelCaseMotion_iw', {noremap = false, silent = true})
-- vim.api.nvim_set_keymap('x', 'iW', '<Plug>CamelCaseMotion_iw', {noremap = false, silent = true})
-- vim.api.nvim_set_keymap('o', 'iB', '<Plug>CamelCaseMotion_ib', {noremap = false, silent = true})
-- vim.api.nvim_set_keymap('x', 'iB', '<Plug>CamelCaseMotion_ib', {noremap = false, silent = true})
-- vim.api.nvim_set_keymap('o', 'ie', '<Plug>CamelCaseMotion_ie', {noremap = false, silent = true})
-- vim.api.nvim_set_keymap('x', 'ie', '<Plug>CamelCaseMotion_ie', {noremap = false, silent = true})
