# `sheldon` configuration file
# ----------------------------

shell = "zsh"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

# 遅延ロードに必要なプラグイン（最初に読み込む）
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
# apply = ["defer"]  # 補完初期化前に読み込む必要があるためdeferを無効化

[plugins.history-search-multi-word]
github = "zdharma/history-search-multi-word"
apply = ["defer"]

# zoxideはHomebrewでインストール済み、初期化のみ行う（遅延読み込み無効）
[plugins.zoxide-init]
inline = 'command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init zsh)" || true'
# apply = ["defer"]  # 遅延読み込みを無効化
