# `sheldon` configuration file
# ----------------------------

shell = "zsh"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

# 遅延ロードに必要なプラグイン（最初に読み込む）
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.history-search-multi-word]
github = "zdharma/history-search-multi-word"
apply = ["defer"]

[plugins.zoxide]
github = "ajeetdsouza/zoxide"
apply = ["defer"]

[plugins.zoxide-init]
inline = 'command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init zsh)" || true'
