abbr "d"="docker"
abbr "dc"="docker compose"
abbr "docker c"="docker compose"
abbr "dcd"="docker compose down"
abbr "dcu"="docker compose up % -d"
abbr "de"="docker exec -it %bash"
abbr "docker e"="docker exec -it %bash"
abbr "docker compose d"="docker compose down"
abbr "docker compose u"="docker compose up %-d"
abbr "docker compose pu"="docker compose --profile % up -d"
abbr "docker compose pd"="docker compose --profile % down"
abbr "dp"="docker ps"
abbr "g"="git"
abbr "ga"="git add"
abbr "git a"="git add"
abbr "gb"="git branch"
abbr "git b"="git branch"
abbr "gc"="git checkout"
abbr "git c"="git checkout"
abbr "gcmt"="git commit"
abbr "git cm"="git commit"
abbr "gd"="git diff"
abbr "git d"="git diff"
abbr "gf"="git fetch --all"
abbr "gg"="git grep"
abbr "git branch clear"="git branch | tr -d '*' | tr -d ' ' | grep -v -x \"main\|develop\" | xargs git branch -D"
abbr "gx"="git branch --all | peco | sed -e \"s/remotes\/origin\///g\" | xargs git checkout"
abbr "git branch x"="git branch --all | peco | sed -e \"s/remotes\/origin\///g\" | xargs git checkout"
abbr "git pull r"="git pull --rebase"
abbr "git push f"="git push --force-with-lease"
abbr "gl"="git show-branch | grep -E \"\*\s*\[\" -A 1 | tail -1 | awk -F'[]~^[]' '{print \$2}' | xargs -Iparent git log parent.."
abbr "gla"="git log --graph --all --decorate"
abbr "gprune"="git prune"
abbr "gpsh"="git push"
abbr "git ps"="git push"
abbr "gpul"="git pull"
abbr "git pl"="git pull"
abbr "gs"="git status"
abbr "gsl"="git stash list"
abbr "gsp"="git stash pop"
abbr "gst"="git stash"
abbr "gsu"="git stash -u"

abbr "poff"="http_proxy= https_proxy="
abbr "gnome logout"="env DISPLAY=:0 gnome-session-quit --logout"

# Claude Code shortcuts
abbr "cl"="claude --dangerously-skip-permissions -c"
abbr "clr"="claude --dangerously-skip-permissions -r"
